services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.2'
    container_name: "elasticsearch"

    environment:
      - 'ELASTIC_USERNAME=admin'
      - 'ELASTIC_PASSWORD=admin'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
  kibana:
     image: "docker.elastic.co/kibana/kibana:8.12.2"
     container_name: "kibana"

     environment:
       - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
     links:
       - 'elasticsearch'
     depends_on:
       - 'elasticsearch'
     ports:
        - '5601:5601'

